apiVersion: v1
kind: Pod
metadata:
  name: continuous-integration
spec:
  containers:
    - name: continuous-integration
      image: jooas/ubuntu-ssh:20.04
      volumeMounts:
        - name: docker-volume
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-volume
      hostPath:
        type: File
        path: /var/run/docker.sock